# Generated by Django 3.2.9 on 2021-12-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('compania', models.CharField(max_length=10)),
                ('conectividad', models.CharField(max_length=3)),
                ('memoria', models.CharField(max_length=6)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('pulgadas', models.IntegerField()),
                ('procesador', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=5)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Televisores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('pulgadas', models.IntegerField()),
                ('resolusion', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
