# Generated by Django 3.2.5 on 2022-01-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=30)),
                ('plazas', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
