# Generated by Django 3.2.5 on 2022-01-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHogar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=30)),
                ('canti_hornallas', models.IntegerField()),
            ],
        ),
    ]
