# Generated by Django 3.2.5 on 2022-01-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHogar', '0002_cocinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodomesticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=30)),
                ('voltage', models.IntegerField()),
            ],
        ),
    ]
